
# See https://www.tiny.cloud/docs/configure/integration-and-setup/#content_css
license_key: 'gpl'

# selector: '.edit'
height: 500
skin: false
remove_linebreaks: false
force_br_newline: true
verify_html: false
convert_urls: false
relative_urls: false
# inline: true


placeholder: 'Type here...'
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_resizing: false
theme_advanced_statusbar_location: bottom
autosave_ask_before_unload: true
autosave_interval: '30s'
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - code
plugins: 'preview searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media codesample table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount help charmap quickbars emoticons accordion'
menubar: 'file edit view insert format tools table help'
toolbar: "undo redo | accordion accordionremove | blocks fontfamily fontsize | bold italic underline strikethrough | align numlist bullist | link image | table media | lineheight outdent indent| forecolor backcolor removeformat | charmap emoticons | code fullscreen preview | save print | pagebreak anchor codesample | ltr rtl"

# image_list: 'documents.jpg'

# importcss_append: true
image_caption: true
image_advtab: true
file_picker_types: 'file image media'
# importcss_exclusive: false
